spring.application.name=billing-accounting
spring.datasource.url=jdbc:postgresql://localhost:5432/billing-accounting-app
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
