spring.application.name=billing-accounting
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_accounting_app
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=190301
=======
spring.datasource.password=
>>>>>>> 654db716695aead34d1e6e09c28979ec431a36f2
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
